### PR TITLE
[FIX] Encode unsafe characters for room title and user's name

### PR DESCRIPTION
**Pull request by debdutdeb**
Closes: #17

### CODE REVIEW

**Comment by ankar84** [comment]
Wow! So fast, Deb!!!!

**Comment by debdutdeb** [comment]
Pierre shared 🙈

**Comment by ankar84** [comment]
@debdutdeb @pierre-lehnen-rc hello!
When merge is planned?

**Comment by debdutdeb** [comment]
Might be this friday, as soon as Pierre come back from his vacation :)

**Pull request merged**
